'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("klinik.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ambulance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ambulance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ambulance1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ambulance1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property atomic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atomic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property blue2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cca1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cca1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cca2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cca2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cca3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cca3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cca4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cca4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cca5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cca5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Exit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fav1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fav1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property icu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Modify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Modify1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modify1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property report2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property reset1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property reset2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property resett() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resett", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property resett1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resett1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ugd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ugd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ugd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ugd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property vc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property vd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property vv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property xz1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xz1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
